### ISSUE TITLE
Building for ARM

### ISSUE THREAD

**Issue by jdevelop** [mxk/go-sqlite#15]
For some reason the build that uses ARM target fails to load the `sqlite3` driver.

The sample code is [here](https://github.com/jdevelop/go-coin-ticker/blob/master/coin_ticker/DataSymbols.go#L146)

The error I get on running the application on ARM:

```
23:04:00.789345 ERR ~ Can't open SQLite3 driver
   _: sql: unknown driver "sqlite3" (forgotten import?)
goroutine 1 [running]:
runtime/debug.Stack(0x10d0cfd8, 0x25a258, 0x10d4c205)
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x80
github.com/mgutz/logxi/v1.(*HappyDevFormatter).getLevelContext(0x10d9d280, 0x3, 0x10dfe400, 0x0, 0x0, 0x0, 0x0, 0x10d108a0, 0x5)
        /home/jdevelop/go/src/github.com/jdevelop/go-coin-ticker/coin_ticker/DataSymbols.go:148 +0xe8
main.main()
        /home/jdevelop/go/src/github.com/jdevelop/go-coin-ticker/Boot.go:93 +0x174

2017/11/27 23:04:00 sql: unknown driver "sqlite3" (forgotten import?)
```

The very same code runs just fine on the host system (`AMD64`).

I build this as

```
GOARCH=arm go build
```

What am I missing?

**Comment by mxk** [comment]
You're looking for https://github.com/mattn/go-sqlite3.
